<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find hector_description)/xacro/transmission.xacro"/>
    <!-- 定义一个宏 leg 传入参数4个 * 符号表示参数是一个列表-->
    <xacro:macro name="leg" params="name mirror mirror_dae  *origin">

        <!-- 连接trunk和hip的关节,注意连接点位置,不在髋关节所在连杆的几何中心 -->
        <!-- 髋关节1的关节 类型为旋转 -->
        <joint name="${name}_hip_joint" type="revolute">
        <!-- 调用xacro包的insert_block  插入了名为 "origin" 的 xacro 块，该块包含了关节的起始位置等信息rpy=0 0 0 xyz=0.0 0.047 -0.1265-->
            <xacro:insert_block name="origin"/>
            <!-- 连接身体和髋关节1 -->
            <parent link="trunk"/>
            <child link="${name}_hip"/>
            <!-- 旋转轴 -->
            <axis xyz="0 0 1"/>
            <!-- 指定关节的动力学参数阻尼和摩擦 -->
            <dynamics damping="${damping}" friction="${friction}"/>
            <!-- 判断是左右腿 从而限制旋转角度-->
            <xacro:if value="${(mirror_dae == True)}">
                <!-- 最大力 最大速度 最小角度 最大角度 -->
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_min*PI/180.0}" upper="${hip_max*PI/180.0}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_max*PI/180.0}" upper="${-hip_min*PI/180.0}"/>
            </xacro:if>
        </joint>
        <!-- 髋关节1所在的部件 -->
        <link name="${name}_hip">
            <visual>
                <!-- 可视化外观的位姿 贴皮肤-->
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <!-- 判断左右腿 -->
                <xacro:if value="${(mirror_dae == True)}">
                    <!-- 贴皮肤 胯关节1的皮肤已经包含了电机和连杆 皮肤只为了可视化,
                    碰撞盒用简单的规则体以减低碰撞时显卡的负载 不建议使用三维软件导出的网格化碰撞盒-->
                    <geometry>
                        <mesh filename="package://hector_description/meshes/R_hip1.STL" scale="1 1 1"/>
                        <!-- 贴皮肤不需要体积数值 box -->
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                   <geometry>
                        <mesh filename="package://hector_description/meshes/L_hip1.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <material name="orange"/>
            </visual>
            <collision>
                <!-- 该位置0.015 0.0 -0.002三个轴都不同于上面jiont 0.0 0.047 -0.1265-->
                <origin rpy="0 0 0" xyz="${hip_x} ${hip_y} ${hip_z}"/>
                <geometry>
                    <!-- 体积极小,只是为了占位 -->
                    <box size="${hip_length} ${hip_width} ${hip_height}"/>
                </geometry>
            </collision>
            <!-- 转动惯量的属性:位姿 重量 转动惯量矩阵 -->
            <inertial>
                <!-- xyz=0.025109 -0.002292 -0.024732-->
                <origin rpy="0 0 0" xyz="${hip_com_x} ${hip_com_y} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia
                    ixx="${hip_ixx}" ixy="${hip_ixy}" ixz="${hip_ixz}"
                    iyy="${hip_iyy}" iyz="${hip_iyz}"
                    izz="${hip_izz}"/>       
            </inertial>
        </link>

        <!--this link is only for motor mass&colllision
            此链接仅适用于电机的质量和碰撞  连接类型:固定-->
        <!-- 髋关节1电机的jiont -->
        <joint name="${name}_hip_trans_joint" type="fixed">
            <!-- 注意位置 xyz=0.079 ±0.015 -0.0705-->
            <origin rpy="0 0 0" xyz="${hip_trans_offset_x} ${hip_trans_offset_y*mirror} ${hip_trans_offset_z}"/>
            <!-- 连接髋关节1和髋关节1电机 -->
            <parent link="${name}_hip"/>
            <child link="${name}_hip_trans"/>
        </joint> 
        
        <!-- 髋关节1电机link -->
        <link name="${name}_hip_trans">
            <collision>
                <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
                <geometry>
                    <!-- 碰撞盒简化为一个圆柱 -->
                    <cylinder length="${hip_trans_length}" radius="${hip_trans_radius}"/>
                </geometry>
            </collision>
            <!-- 转动惯量的属性:位姿 重量 转动惯量矩阵 -->
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="${hip_trans_mass}"/>
                <inertia
                    ixx="${hip_trans_ixx}" ixy="${hip_trans_ixy}" ixz="${hip_trans_ixz}"
                    iyy="${hip_trans_iyy}" iyz="${hip_trans_iyz}"
                    izz="${hip_trans_izz}"/>       
            </inertial>
        </link>
        <!-- 髋关节2的关节 类型:旋转-->
        <joint name="${name}_hip2_joint" type="revolute">
            <!-- 注意位置 xyz=0.0465 0.015 -0.0705 -->
            <origin rpy="0 0 0" xyz="${hip2_offset_x} ${hip2_offset_y*mirror} ${-hip2_offset_z}"/>
            <!-- 连接髋关节1和髋关节2 -->
            <parent link="${name}_hip"/>
            <child link="${name}_hip2"/>
            <!-- 旋转轴 -->
            <axis xyz="1 0 0"/>
            <!-- 弹簧系数和摩擦系数 -->
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${hip2_torque_max}" velocity="${hip2_velocity_max}" lower="${hip2_min*PI/180.0}" upper="${hip2_max*PI/180.0}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip2_torque_max}" velocity="${hip2_velocity_max}" lower="${-hip2_max*PI/180.0}" upper="${-hip2_min*PI/180.0}"/>
            </xacro:if>
        </joint>
        <!-- 髋关节2的关节所在的部件 -->
        <link name="${name}_hip2">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://hector_description/meshes/R_hip2.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                   <geometry>
                        <mesh filename="package://hector_description/meshes/L_hip2.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <material name="red"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="-0.1 0 0"/>
                <geometry>
                    <box size="${hip2_length} ${hip2_width} ${hip2_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="-0.033217 -0.010231 0"/>
                <mass value="${hip2_mass}"/>
                <inertia
                    ixx="${hip2_ixx}" ixy="${hip2_ixy}" ixz="${hip2_ixz}"
                    iyy="${hip2_iyy}" iyz="${hip2_iyz}"
                    izz="${hip2_izz}"/>       
            </inertial>
        </link>
     
        <!--this link is only for collision-->
        <joint name="${name}_hip2_trans_joint" type="fixed">
            <!-- xyz=-0.06 -0.015 0.0 -->
            <origin rpy="0 0 0" xyz="${hip2_trans_offset_x} ${hip2_trans_offset_y*mirror} ${hip2_trans_offset_z}"/>
            <parent link="${name}_hip2"/>
            <child link="${name}_hip2_trans"/>
        </joint> 

        <link name="${name}_hip2_trans">
            <collision>
                <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${hip2_trans_length}" radius="${hip2_trans_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
                <mass value="${hip2_trans_mass}"/>
                <inertia
                    ixx="${hip2_trans_ixx}" ixy="${hip2_trans_ixy}" ixz="${hip2_trans_ixz}"
                    iyy="${hip2_trans_iyy}" iyz="${hip2_trans_iyz}"
                    izz="${hip2_trans_izz}"/>       
            </inertial>
        </link>
        
        <joint name="${name}_thigh_joint" type="revolute">
            <xacro:if value="${mirror_dae == True}">
                <!-- xy= -0.06 0.018 0 -->
                <origin rpy="0 ${0.25*PI} 0" xyz="${thigh_offset_x} ${mirror*thigh_offset_y} ${thigh_offset_z}"/>
            </xacro:if>
            <xacro:if value="${mirror_dae == False}">
                <origin rpy="0 ${0.25*PI} 0" xyz="${thigh_offset_x} ${thigh_offset_y} ${thigh_offset_z}"/>
            </xacro:if>
            <!-- 连接髋关节2和大腿 -->
            <parent link="${name}_hip2"/>
            <child link="${name}_thigh"/>
            <!-- 旋转轴 -->
            <axis xyz="0 1 0"/>
            <joint_properties damping="${damping}" friction="${friction}"/>
            <!-- <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}"/> -->
            <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_min}" upper="${thigh_max}"/>
        </joint>

        <link name="${name}_thigh">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://hector_description/meshes/R_thigh.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                   <geometry>
                        <mesh filename="package://hector_description/meshes/L_thigh.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <material name="white"/>
            </visual>
            <collision>
                <!-- xyz=0.0 0.0175 -0.09 -->
                <origin rpy="0 0 0" xyz="${thigh_x} ${thigh_y*mirror} ${thigh_z}"/>
                <geometry>
                    <box size="${thigh_length} ${thigh_width} ${thigh_height}"/>
                </geometry>
            </collision>
             <inertial>
                <!-- xyz=-0.000147 0.01991 -0.081117 -->
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}"/>
                <mass value="${thigh_mass}"/>
                <inertia
                    ixx="${thigh_ixx}" ixy="${thigh_ixy}" ixz="${thigh_ixz}"
                    iyy="${thigh_iyy}" iyz="${thigh_iyz}"
                    izz="${thigh_izz}"/>       
            </inertial>
        </link>

        <!--this link is only for collision-->
        <joint name="${name}_thigh1_trans_joint" type="fixed">
            <!-- xyz=0.0 0.0625 0.0 -->
            <origin rpy="0 0 0" xyz="${thigh1_trans_offset_x} ${thigh1_trans_offset_y*mirror} ${thigh1_trans_offset_z}"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_thigh1_trans"/>
        </joint> 

        <link name="${name}_thigh1_trans">
            <collision>
                <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${thigh1_trans_length}" radius="${thigh1_trans_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
                <mass value="${thigh1_trans_mass}"/>
                <inertia
                    ixx="${thigh1_trans_ixx}" ixy="${thigh1_trans_ixy}" ixz="${thigh1_trans_ixz}"
                    iyy="${thigh1_trans_iyy}" iyz="${thigh1_trans_iyz}"
                    izz="${thigh1_trans_izz}"/>       
            </inertial>
        </link>

        <!--this link is only for collision-->
        <joint name="${name}_thigh2_trans_joint" type="fixed">
            <!-- xyz=0.0 -0.0225 -0.097 -->
            <origin rpy="0 0 0" xyz="${thigh2_trans_offset_x} ${thigh2_trans_offset_y*mirror} ${thigh2_trans_offset_z}"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_thigh2_trans"/>
        </joint>  

        <link name="${name}_thigh2_trans">
            <collision>
                <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${thigh2_trans_length}" radius="${thigh2_trans_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="${-PI/2} 0 0" xyz="0 0 0"/>
                <mass value="${thigh2_trans_mass}"/>
                <inertia
                    ixx="${thigh2_trans_ixx}" ixy="${thigh2_trans_ixy}" ixz="${thigh2_trans_ixz}"
                    iyy="${thigh2_trans_iyy}" iyz="${thigh2_trans_iyz}"
                    izz="${thigh2_trans_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_calf_joint" type="revolute">
            <!-- xyz=0.0 0.0*0 -0.22 -->
            <origin rpy="0 ${-0.5*PI} 0" xyz="${calf_offset_x} ${0} ${-calf_offset_z}"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_calf"/>
            <!-- 旋转轴 -->
            <axis xyz="0 1 0"/>
            <joint_properties damping="${damping}" friction="${friction}"/>
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_min}" upper="${calf_max}"/>
        </joint>

        <link name="${name}_calf">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://hector_description/meshes/R_calf.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                   <geometry>
                        <mesh filename="package://hector_description/meshes/L_calf.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <material name="orange"/>
            </visual>
            <collision>
                <!-- xyz=0.0 0.02*0 -0.11 -->
                <origin rpy="0 0 0" xyz="${calf_x} ${calf_y*0} ${calf_z}"/>
                <geometry>
                    <cylinder length="${calf_length}" radius="${calf_radius}"/>
                </geometry>      
            </collision>
            <inertial>
                <!-- xyz=0.0 0.020417 -0.1141 -->
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y*mirror} ${calf_com_z}"/>
                <mass value="${calf_mass}"/>
                <inertia
                    ixx="${calf_ixx}" ixy="${calf_ixy}" ixz="${calf_ixz}"
                    iyy="${calf_iyy}" iyz="${calf_iyz}"
                    izz="${calf_izz}"/>       
            </inertial>
        </link>

        <joint name="${name}_toe_joint" type="revolute">
            <!-- xyz=0.0 0.0*0 -0.22 -->
            <origin rpy="0 ${0.25*PI} 0" xyz="${toe_offset_x} ${toe_offset_y*0} ${toe_offset_z}"/>
            <parent link="${name}_calf"/>
            <child link="${name}_toe"/>
            <!-- 旋转轴 -->
            <axis xyz="0 1 0"/>
            <joint_properties damping="${damping}" friction="${friction}"/>
            <limit effort="${toe_torque_max}" velocity="${toe_velocity_max}" lower="${toe_min}" upper="${toe_max}"/>
        </joint>

        <link name="${name}_toe">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://hector_description/meshes/R_foot.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                   <geometry>
                        <mesh filename="package://hector_description/meshes/L_foot.STL" scale="1 1 1"/>
                    </geometry>
                </xacro:if>
                <material name="red"/>
            </visual>
            <collision>
                <!-- xyz=0.01 0.0194 -0.02 -->
                <origin rpy="0 0 0" xyz="${toe_x} ${toe_y*mirror} ${toe_z}"/>
                <geometry>
                     <!--0.15 0.02 0.04  -->
                    <box size="${toe_length} ${toe_width} ${toe_height}"/>
                </geometry>      
            </collision>
            <inertial>
                <!-- xyz=0.010569 0.017949 -0.017118 -->
                <origin rpy="0 0 0" xyz="${toe_com_x} ${toe_com_y*mirror} ${toe_com_z}"/>
                <mass value="${toe_mass}"/>
                <inertia
                    ixx="${toe_ixx}" ixy="${toe_ixy}" ixz="${toe_ixz}"
                    iyy="${toe_iyy}" iyz="${toe_iyz}"
                    izz="${toe_izz}"/>       
            </inertial>
        </link>
       
        <xacro:leg_transmission name="${name}"/>
    </xacro:macro>
</robot>
